# Markets v1.0 by sniddunc

General:
  AutosaveDelay: 300 #delay in seconds between autosaves
  PriceUpdateDelay: 30 # delay in seconds between value increases
  EnableBuyScaling: true
  EnableSellScaling: true

Signs:
  BuyLineBefore: "[Buy]"
  BuyLineAfter: "&1[Buy]"
  SellLineBefore: "[Sell]"
  SellLineAfter: "&1[Sell]"

Prices:
  COAL:
    Buy: 6.0
    Sell: 3.0
    Change: 0.12
  IRON_INGOT:
    Buy: 20.0
    Sell: 10.0
    Change: 0.4
  GOLD_INGOT:
    Buy: 100.0
    Sell: 50.0
    Change: 2.0
  DIAMOND:
    Buy: 1000.0
    Sell: 500.0
    Change: 20.0