name: Markets
version: 1.0-SNAPSHOT
main: com.dmastech.markets.Markets
api-version: 1.13
depend: [Vault, ActionBarAPI]
authors: [sniddunc]
website: dmastech.com
commands:
  markets:
    description: Command displaying market info